version: 2
jobs:
  dependencies:
    override:
      - sudo pip install awscli
  build:
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    working_directory: ~/googletranslate
    steps:
      - checkout
      - run: gradle wrapper
      - run: ./gradlew :googletranslaterepeater:clean :googletranslaterepeater:shadowJar
  test:
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    working_directory: ~/googletranslate
    steps:
      - checkout
      - run: gradle test
  deploy:
    production:
      branch: master
      commands:
        -  aws s3 sync /home/ubuntu/googletranslate s3://nathan-butler.com/googletranslate/ --delete
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - dependencies
      - build
      - test