version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    working_directory: ~/googletranslate
    steps:
      - checkout
      - run: gradle wrapper
      - run: ./gradlew :googletranslaterepeater:clean :googletranslaterepeater:shadowJar
  test:
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    working_directory: ~/googletranslate
    steps:
      - checkout
      - run: gradle test
  deployment:
    staging:
      branch: development
      codedeploy:
        googletranslate:
          deployment_group: staging-instance-group
    production:
      branch: master
      codedeploy:
        googletranslate:
          deployment_group: production-instance-group
  run:
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    working_directory: ~/googletranslate
    steps:
      - checkout
      - run: java -jar googletranslaterepeater/root.jar server googletranslaterepeater/local.yaml
workflows:
  version: 2
  build_test_deployment:
    jobs:
      - build
      - test
      - deployment