version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    working_directory: ~/googletranslate
    steps:
      - checkout
      - run: gradle wrapper
      - run: ./gradlew :googletranslaterepeater:clean :googletranslaterepeater:shadowJar
  run:
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    working_directory: ~/googletranslate
    steps:
      - checkout
      - run: java -jar googletranslaterepeater/root.jar server googletranslaterepeater/local.yaml
  deployment:
    staging:
      branch: master
      codedeploy:
        googletranslate:
          deployment_group: Bot
workflows:
  version: 2
  build_run_deploy:
    jobs:
      - build
      - run