version: 2
dependencies:
    override:
        - sudo pip install awscli
deployment:
  prod:
    branch: master
    commands:
      - aws s3 sync /home/ubuntu/googletranslate s3://nathan-butler.com --delete