version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    working_directory: ~/googletranslate
    steps:
      - checkout
      - run: sudo pip install awscli
      - run: gradle wrapper
      - run: ./gradlew :googletranslaterepeater:clean :googletranslaterepeater:shadowJar
  test:
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    working_directory: ~/googletranslate
    steps:
      - checkout
      - run: gradle test
workflows:
  version: 2
  build_test_deployment:
    jobs:
      - build
      - test
